#!/bin/sh

# ==============================================================================
#   Preflight script for ipfw-configuration installer
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ==============================================================================

# Change to match the actual item (if needed):
LAUNCHD_ITEM_NAME="com.github.hjuutilainen.ipfw"

NOW=$(date +"%Y-%m-%d-%H%M%S")
BACKUPDIR="$3/var/backups/ipfw-$NOW"
mkdir "$BACKUPDIR"
LAUNCHCTL="/bin/launchctl"
IPFW_LAUNCHD_ITEM="/Library/LaunchDaemons/$LAUNCHD_ITEM_NAME.plist"

echo "$SCRIPT_NAME: Backup directory is $BACKUPDIR"

# Unload and backup the old launchd item
if [[ "$3" == "/" ]]; then
    echo $SCRIPT_NAME: Installing on startup volume
    if [[ -f "$IPFW_LAUNCHD_ITEM" ]]; then
		$LAUNCHCTL list com.github.hjuutilainen.ipfw
		if [[ $? -eq 0 ]]; then
	    	$LAUNCHCTL unload -w "$IPFW_LAUNCHD_ITEM"
		fi
		cp "$IPFW_LAUNCHD_ITEM" "$BACKUPDIR/$LAUNCHD_ITEM_NAME-$NOW.plist"
    fi
fi

# Backup the /etc/ipfw directory
if [[ -d "$3/etc/ipfw/" ]]; then
    echo "$SCRIPT_NAME: Backing up /etc/ipfw components"
    cp -R "$3/etc/ipfw" "$BACKUPDIR/ipfw-$NOW"
fi


exit 0
